set(KIN_EASY_USE_LIB 1)

set(BIN_FILE_PATH bin/${CMAKE_CXX_COMPILER_ID}/${CMAKE_BUILD_TYPE})
set(EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/${BIN_FILE_PATH})
set(LIBRARY_OUTPUT_PATH ${EXECUTABLE_OUTPUT_PATH})

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} $ENV{KinBase}/KinLua)
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} $ENV{KinBase}/spdlog)
